<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
			<PrivatePropertys>all</PrivatePropertys>
			<IncludePropertys>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludePropertys>
		</PackageReference>
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Middlewares\" />
		<Folder Include="wwwroot\Images\Properties\" />
		<Folder Include="wwwroot\Images\Users\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Sis_Inmobiliaria.Core.Application\Sis_Inmobiliaria.Core.Application.csproj" />
	  <ProjectReference Include="..\Sis_Inmobiliaria.Core.Domain\Sis_Inmobiliaria.Core.Domain.csproj" />
	  <ProjectReference Include="..\Sis_Inmobiliaria.Infrastructure.Identity\Sis_Inmobiliaria.Infrastructure.Identity.csproj" />
	  <ProjectReference Include="..\Sis_Inmobiliaria.Infrastructure.Persistence\Sis_Inmobiliaria.Infrastructure.Persistence.csproj" />
	  <ProjectReference Include="..\Sis_Inmobiliaria.Infrastructure.Shared\Sis_Inmobiliaria.Infrastructure.Shared.csproj" />
	</ItemGroup>
</Project>
